version: "3.6"
services:
  fast_user_api:
    build: .
    command: bash -c "sh /code/scripts/scripts_set_app/setup_app.sh && python /code/libs/server/server.py"
    env_file:
      - .env
    container_name: fast_user_api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - fast_user_db
    restart: always

  fast_user_db:
    image: mongo:latest
    container_name: fast_user_db
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"
    restart: always


volumes:
  mongo-db: {}