version: "3.6"
services:
  fast_user_api:
    build: .
    command: bash -c "sh /code/scripts/scripts_set_app/setup_app.sh &&
                      # python /code/cli_commands/commands/filled_store &&
                      python /code/core/server.py"
    env_file:
      - .env
    container_name: fast_user_api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - fast_user_db
    restart: always

  fast_user_db:
    image: mongo:latest
    container_name: fast_user_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - mongo-db:/data/db
      - ./scripts/scripts_set_db/set_db.sh:/docker-entrypoint-initdb.d/set_db.sh:ro
    restart: always


volumes:
  mongo-db: {}